const mongoose = require('mongoose');

const documentChunkSchema = new mongoose.Schema({
    mediaId: { type: mongoose.Schema.Types.ObjectId, ref: 'Media', required: true },
    text: { type: String, required: true },
    // This array will hold the 384-dimensional vector generated by our local embedding model
    embedding: { type: [Number], required: true }, 
    chunkIndex: { type: Number, required: true }
});

module.exports = mongoose.model('DocumentChunk', documentChunkSchema);